<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Herms Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/style.default.css'))
                        ->prependStylesheet($this->basePath('vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css'))
                        ->prependStylesheet($this->basePath('css/grasp_mobile_progress_circle-1.0.0.min.css'))
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,400,500,700')
                        ->prependStylesheet($this->basePath('css/fontastic.css'))
                        ->prependStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('vendor/bootstrap/css/bootstrap.min.css'));
                        
						
        ?>
    <!-- Tweaks for older IEs-->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
        
        
    </head>
    <body class="hold-transition login-page">
			<?= $this->Success();?>
			<?= $this->Error();?>
            <?= $this->content; ?>
            
            
        <?= $this->inlineScript()->prependFile('https://code.jquery.com/jquery-3.2.1.min.js') ?>
        <?= $this->inlineScript()->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js') ?>
        <?= $this->inlineScript()->prependFile($this->basePath('vendor/bootstrap/js/bootstrap.min.js')) ?>    
		<?= $this->inlineScript()->prependFile($this->basePath('vendor/jquery.cookie/jquery.cookie.js')) ?>
		<?= $this->inlineScript()->prependFile($this->basePath('js/grasp_mobile_progress_circle-1.0.0.min.js')) ?>
		<?= $this->inlineScript()->prependFile($this->basePath('vendor/jquery-validation/jquery.validate.min.js')) ?>
		<?= $this->inlineScript()->prependFile($this->basePath('vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js')) ?>
        <?= $this->inlineScript()->prependFile($this->basePath('js/front.js')) ?>
        
        
    </body>
</html>
