    <div class="page login-page">
      <div class="container">
        <div class="form-outer text-center d-flex align-items-center">
          <div class="form-inner">
            <div class="logo text-uppercase"><span><?php var_dump($this->appdata)?></span><strong class="text-primary">Dashboard</strong></div>
            <p>Login to Manage your account</p>
                <?php
                $form->prepare();
                $form->setAttribute('action', $this->url('login'));
                $form->setAttribute('id', 'login-form');
                echo $this->form()->openTag($form);
                ?>
                <?php echo $this->formInput( $form->get('secureprefix')->setAttribute( 'value' , $this->SecureKey() ) ); ?>
              <div class="form-group">
                <label for="login-username" class="label-custom">Email</label>
                <?php echo $this->formelement( $form->get('userlogin') )?>
              </div>
              <div class="form-group">
                <label for="login-password" class="label-custom">Password</label>
                <?php echo $this->formelement( $form->get('pw') )?>
              </div>
				<div class="form-group">
               		<button type="submit" class="btn btn-primary">Login</button>
              	</div>
              
              <!-- This should be submit button but I replaced it with <a> for demo purposes-->
            
				<?php echo $this->form()->closeTag($form)?>
				<a href="<?php echo $this->url('login/resetpassword');?>" class="forgot-pass">Forgot Password?</a>
				<small>Do not have an account? </small><a href="register.html" class="signup">Signup</a>
          </div>
          <div class="copyrights text-center">
            <p>Design by <a href="https://bootstrapious.com" class="external">Bootstrapious</a></p>
            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
          </div>
        </div>
      </div>
    </div>